<?php
	require_once('../includes/dbConnect.php');
	require_once('../classes/Tools.php');
	require_once('../includes/bdd.php');
	$content=$_POST["CONTENT"];
	$category=$_POST["CATEGORY"];
	$date=$_POST["DATE"];
	$end_date=$_POST["END_TYPE_TASK"];
	Tools::addTask($category,$content,$date,$end_date);
?>